### ISSUE TITLE
Need a common place for utilities between broadcast & privatemessaging

### ISSUE THREAD

**Issue by awrichar** [hyperledger-labs/firefly#159]
The function `SubmitPinnedBatch` lives in the `broadcast` package but is used by both `broadcast` and `privatemessaging`. Need a better place for this (and possibly any other common code between the two).

https://github.com/hyperledger-labs/firefly/blob/8fef7ce0e03899a097167e80b6d1cf0d938b313c/internal/broadcast/manager.go#L97

**Comment by peterbroadhurst** [comment]
Was thinking whether in the refactoring I did that resulted in `syshandlers` and `sysmessaging` there's anything that helps - but sadly not.

I think this would require a new `batchpin` package (that would put it next to `batch` in the dir listing, which is logically where it would otherwise go if import cycles weren't a thing).
